# package submodule
- hosts: localhost
  tasks:
  - name: git update submodule
    command: git submodule init && git submodule update && git submodule update --recursive --remote
    args:
      chdir: "{{ playbook_dir }}"
  - name: archive helm project to package floor
    archive:
      path: "{{ playbook_dir }}/elk-stack-helm"
      dest: "{{ playbook_dir }}/package/elk-stack.tgz"

- hosts: k8s
  roles: 
  # install elk into kubernetes
  - role: init

- hosts: helm_host
  roles: 
  # install elk into kubernetes
  - role: install_elk
    cluster_name: awcloud-log
    params: pod.replicas.master=3,pod.replicas.data=3,pod.replicas.ingest=3,storage.storage_class=rook
    elk_namespace: awcloud-log

- hosts: client_host
  vars:
    host_name: 192.168.250.200:31200
    kibana_host: 192.168.250.200:31203
  roles:
  #Install packetbeat
  - role: install_beats
    config_name: packetbeat.yml
    rpm_name: packetbeat.rpm
    service_name: packetbeat
  #Install metricbeat
  - role: install_beats
    config_name: metricbeat.yml
    rpm_name: metricbeat.rpm
    service_name: metricbeat
  #Install filebeat
  - role: install_beats
    config_name: filebeat.yml
    rpm_name: filebeat.rpm
    service_name: filebeat
    # 注意多行情况下从第二行开始需要自定加空格保证yaml文件格式正确
    log_paths: |
      - /var/log/*.log
          - /var/log/logs/*.log
          - /var/log/a.log
  #Install auditbeat
  - role: install_beats
    config_name: auditbeat.yml
    rpm_name: auditbeat.rpm
    service_name: auditbeat

- hosts: client_host
  roles: 
  # init packetbeat dashboard
  - role: init_dashboard
    command_name: packetbeat
  # init metricbeat dashboard
  - role: init_dashboard
    command_name: metricbeat
  # init filebeat dashboard
  - role: init_dashboard
    command_name: filebeat
  # init auditbeat dashboard
  - role: init_dashboard
    command_name: auditbeat
  
- hosts: client_host
  roles: 
  # start service : packetbeat 
  - role: start_service
    service_name: packetbeat
  # istart service : metricbeat
  - role: start_service
    service_name: metricbeat
  # start service : filebeat 
  - role: start_service
    service_name: filebeat
  # start service :auditbeat
  - role: start_service
    service_name: auditbeat

