- hosts: k8s
  tasks:
    - name: stop and disable firewall
      systemd: 
        name: firewalld
        state: stopped
        enabled: no
    - name: disable selinux
      command: "setenforce 0"
    - name: stop selinux 
      selinux:
        state: disabled